# Generated by Django 4.0.4 on 2023-10-31 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the admin', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter a admin username', max_length=100)),
                ('email', models.CharField(help_text='Enter a client email', max_length=100)),
                ('password', models.CharField(help_text='Enter a password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the client', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter a client username', max_length=100)),
                ('email', models.CharField(help_text='Enter a client email', max_length=100)),
                ('salt', models.CharField(default=None, help_text='Enter a salt', max_length=100)),
                ('hashed_password', models.CharField(default=None, help_text='Enter a hash', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the bank account', primary_key=True, serialize=False)),
                ('savings', models.FloatField()),
                ('client_id', models.ForeignKey(help_text='The ID of the client using this account', on_delete=django.db.models.deletion.CASCADE, to='fintech_testbed_app.client')),
            ],
        ),
    ]
