# Generated by Django 4.2.7 on 2023-11-07 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_testbed_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the transactions', primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
                ('datetime', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('bank_id', models.ForeignKey(help_text='The ID of the bamkaccount', on_delete=django.db.models.deletion.CASCADE, to='fintech_testbed_app.bankaccount')),
                ('reciever', models.ForeignKey(help_text='The ID of the client', on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='fintech_testbed_app.client')),
                ('sender', models.ForeignKey(help_text='The ID of the client', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='fintech_testbed_app.client')),
            ],
        ),
    ]
