# Generated by Django 4.2.7 on 2023-11-17 03:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_testbed_app', '0002_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the admin', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter a admin username', max_length=100)),
                ('email', models.CharField(help_text='Enter a client email', max_length=100)),
                ('salt', models.CharField(default=None, help_text='Enter a salt', max_length=100)),
                ('hashed_password', models.CharField(default=None, help_text='Enter a hash', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='hashed_password',
            field=models.CharField(default=None, help_text='Enter a hash', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='salt',
            field=models.CharField(default=None, help_text='Enter a salt', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reciever',
            field=models.ForeignKey(default=None, help_text='The ID of the client', on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='fintech_testbed_app.client'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sender',
            field=models.ForeignKey(default=None, help_text='The ID of the client', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='fintech_testbed_app.client'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
